#!/bin/bash -l

set -e

app=bigcouch
user=$app

if [ -f /etc/default/$app ]
then
    . /etc/default/$app
fi

: ${ERLANG_THREADS:=25}

# options: debug info warning error none
: ${BIGCOUCH_LOG_LEVEL:=info}

: ${BIGCOUCH_DATA_PATH:=/data/$app}
: ${BIGCOUCH_BIND_ADDR:=0.0.0.0}

: ${BIGCOUCH_REQUIRE_VALID_USER:=false}
: ${BIGCOUCH_ADMIN_USER:=admin}
: ${BIGCOUCH_ADMIN_PASS:=secret}

: ${BIGCOUCH_SHARDS:=4}
: ${BIGCOUCH_READ_QUORUM:=1}
: ${BIGCOUCH_WRITE_QUORUM:=1}
: ${BIGCOUCH_REPLICAS:=3}
: ${BIGCOUCH_ZONES:=1}


function log 
{
    local msg="$1"
    echo -e "\E[36m[*]\E[0m ${msg}" 
}


if [[ $KUBERNETES_HOSTNAME_FIX = true ]]
then
    eval $(fix-kube-hostname enable)
fi


if [[ $PERSISTENT_STORAGE_ENABLED = true ]]
then 
    persist-volume-util link $app
fi


log "Writing erlang cookie ..." 
write-erlang-cookie


log "Writing vm.args file ..."
tee ~/etc/vm.args <<EOF
# Turn off the sasl error logger
-sasl sasl_error_logger false

# Use the following erlang long hostname
-name bigcouch@$(hostname -f)

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A $ERLANG_THREADS

# Turn off the kernel error_logger
-kernel error_logger silent 

# Set erlang distribution to use 11500-11999 ports instead of random
# predictibility has value here
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999

# Comment this line out if you want the Erlang shell
+Bd -noinput

# User the following config files
-couch_ini /opt/bigcouch/etc/default.ini /opt/bigcouch/etc/local.ini
EOF


log "Rewriting local.ini file ..."
tee ~/etc/local.ini <<EOF
[couchdb]
database_dir = $BIGCOUCH_DATA_PATH
view_index_dir = $BIGCOUCH_DATA_PATH

[chttpd]
require_valid_user = $BIGCOUCH_REQUIRE_VALID_USER
port = 5984
bind_address = $BIGCOUCH_BIND_ADDR

[httpd]
require_valid_user = $BIGCOUCH_REQUIRE_VALID_USER
port = 5986
bind_address = $BIGCOUCH_BIND_ADDR

[cluster]
q=$BIGCOUCH_SHARDS
r=$BIGCOUCH_READ_QUORUM
w=$BIGCOUCH_WRITE_QUORUM
n=$BIGCOUCH_REPLICAS
z=$BIGCOUCH_ZONES

[log]
level = $BIGCOUCH_LOG_LEVEL
file = 
EOF


log "Ensuring correct permissions ..."
chown -R $user:$user \
    ~ \
    ~/etc \
    /volumes/$app \
    /data/$app \
    /opt/bigcouch/etc \


cd ~
    log "Starting $app ..."
    export ERL_CRASH_DUMP=$(date +%s)_${app}_crash.dump

    # this script handles annoying post-init tasks automatically,
    # and deletes ~/.init-node
    [[ -f ~/.init-node ]] && ~/init-node.sh > /dev/null 2>&1 &
    
    exec gosu $user bigcouch 2>&1
