#!/bin/bash

BIGCOUCH_SASL_LOGLEVEL=${BIGCOUCH_SASL_LOGLEVEL:-error}
BIGCOUCH_THREADS=${BIGCOUCH_THREADS:-25}
BIGCOUCH_LOG_LEVEL=${BIGCOUCH_LOG_LEVEL:-info}

BIGCOUCH_CHTTPD_PORT=${BIGCOUCH_CHTTPD_PORT:-5984}
BIGCOUCH_CHTTPD_BINDADDR=${BIGCOUCH_CHTTPD_BINDADDR:-0.0.0.0}
BIGCOUCH_HTTPD_PORT=${BIGCOUCH_HTTPD_PORT:-5986}
BIGCOUCH_HTTPD_BINDADDR=${BIGCOUCH_HTTPD_BINDADDR:-0.0.0.0}

ERLANG_NODE=${ERLANG_NODE:-bigcouch}

# Die on error
set -e

# FUNCTIONS
link_erlang_cookie() {
    if [ -f '/etc/secrets/erlang/cookie' ]; then
        echo "Linking Erlang Cookie"
        yes | cp -rf /etc/secrets/erlang/cookie ~/.erlang.cookie
        # ln -sf /etc/secrets/erlang/cookie ~/.erlang.cookie
        chown bigcouch:bigcouch /opt/bigcouch/.erlang.cookie
        chmod 0600 /opt/bigcouch/.erlang.cookie
    else
        echo "*** No Erlang Cookie Mounted! ***"
        echo insecure-cookie > ~/.erlang.cookie
        chown bigcouch:bigcouch /opt/bigcouch/.erlang.cookie
        chmod 0600 /opt/bigcouch/.erlang.cookie
    fi
}

get_etcd_host() {
    local HOST=$(dig +short +search etcd-client)
    echo -n $HOST
}

get_etcd_port() {
    local PORT=$(dig +short +search SRV _etcd-client-port._tcp.etcd-client | awk '{print $3}')
    echo -n $PORT
}

if [ -n "$KUBERNETES_HOSTNAME_FIX" ]; then
    echo "Applying kubernetes hostname fix"
    ln -sf /opt/bigcouch/bin/hostname-fix /opt/bigcouch/bin/hostname
    chown bigcouch:bigcouch /opt/bigcouch/bin/hostname
    export HOSTNAME=$(/opt/bigcouch/bin/hostname-fix)
    echo "127.0.0.1    $HOSTNAME" >> /etc/hosts
fi

echo "Writing vm.args file ..."
tee /opt/bigcouch/etc/vm.args <<EOF
-name $ERLANG_NODE@$(env hostname -f)
-sasl errlog_type $BIGCOUCH_SASL_LOGLEVEL
+K true
+A $BIGCOUCH_THREADS
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999
+Bd -noinput
-couch_ini /opt/bigcouch/etc/default.ini /opt/bigcouch/etc/local.ini
EOF
chown bigcouch:bigcouch /opt/bigcouch/etc/vm.args
chmod 0777 /opt/bigcouch/etc/vm.args

if [ -f '/etc/secrets/bigcouch/secret' ]; then
    BIGCOUCH_ADMIN_SECRET=$(cat /etc/secrets/bigcouch/secret)
    echo "Admin secret successfuly read from secret volume file ..."
else
    BIGCOUCH_ADMIN_SECRET=some-horrible-default
    echo "*** No secret file found at /etc/secrets/bigcouch/secret, using insecure backup ***"
fi

echo "Writing local.ini file ..."
rm -f /opt/bigcouch/etc/local.ini
tee /opt/bigcouch/etc/local.ini <<EOF
[admins]
admin = $BIGCOUCH_ADMIN_SECRET

[couchdb]
database_dir = /var/lib/bigcouch
view_index_dir = /var/lib/bigcouch

[chttpd]
secret = $BIGCOUCH_ADMIN_SECRET
require_valid_user = true
port = $BIGCOUCH_CHTTPD_PORT
bind_address = $BIGCOUCH_CHTTPD_BINDADDR

[httpd]
secret = $BIGCOUCH_ADMIN_SECRET
require_valid_user = true
port = $BIGCOUCH_HTTPD_PORT
bind_address = $BIGCOUCH_HTTPD_BINDADDR

[cluster]
q=1
r=1
w=1
n=1
z=1

[log]
file = /var/log/bigcouch/bigcouch.log
level = $BIGCOUCH_LOG_LEVEL
EOF

mkdir -p /tmp/bigcouch
chown bigcouch:bigcouch /tmp/bigcouch

echo "linking erlang cookie"
link_erlang_cookie

echo "Ensuring Permissions"
chown -R bigcouch:bigcouch /var/lib/bigcouch
chmod -R 0755 /opt/bigcouch /var/lib/bigcouch
chmod 0600 ~/.erlang.cookie

cd ~
    echo "Starting Bigcouch ..."
    export BEAM=beam
    export PATH=/opt/bigcouch/bin:/opt/bigcouch/erts-5.8.2/bin:$PATH
    export ERL_CRASH_DUMP=$(date +%s)_bigcouch_erl_crash.dump
    export ERL_LIBS=/opt/bigcouch/lib:$ERL_LIBS
    
    su bigcouch -c 'exec /opt/bigcouch/bin/bigcouch'
