apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bigcouch
spec:
  template:
    metadata:
      name: bigcouch
      labels:
        app: bigcouch
        project: valuphone
        role: document-db
    spec:
      # nodeSelector: 
      #   kubernetes.io/hostname: adeno.valuphone.com
      hostNetwork: true
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
        - name: bigcouch-admin-secret
          secret:
            secretName: bigcouch-admin-secret
        - name: bigcouch-data
          persistentVolumeClaim:
            claimName: bigcouch-data
      containers:
        - name: bigcouch
          image: callforamerica/bigcouch
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
            - name: bigcouch-admin-secret
              readOnly: true
              mountPath: /etc/secrets/bigcouch
            - name: bigcouch-data
              mountPath: /mnt/bigcouch-data
          env:
            - name: MOUNT_PERSISTENT_VOLUME
              value: 'true'
            # - name: KUBERNETES_HOSTNAME_FIX
            #   value: 'false'
            # - name: BIND_INTERFACE
            #   value: bond0
          ports:
            - name: data
              protocol: TCP
              containerPort: 5984
            - name: admin
              protocol: TCP
              containerPort: 5986
          resources:
            requests:
              cpu: 2
              memory: 4G
            # limits:
            #   cpu: 
            #   memory: 
          # readinessProbe:
          #   httpGet:
          #     path: /_stats
          #     port: 5986
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /_stats
          #     port: 5986
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
      restartPolicy: Always