apiVersion: v1
kind: Service
metadata:
  name: bigcouch-bal
spec:
  selector:
    app: bigcouch
    project: valuphone
    environment: production
  ports:
  - name: data
    protocol: TCP
    port: 5984
  - name: admin
    protocol: TCP
    port: 5986
