apiVersion: v1
kind: PersistentVolume
metadata:
  name: bigcouch-bigcouch-0
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bigcouch-bigcouch-1
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bigcouch-bigcouch-2
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
