kind: Endpoints
apiVersion: v1
metadata:
  name: bigcouch
subsets:
  - addresses:
    - ip: 10.56.63.187
    - ip: 10.56.63.151
    - ip: 10.56.63.130
    ports:
      - name: data
        protocol: TCP
        port: 5984
      - name: admin
        protocol: TCP
        port: 5986