apiVersion: v1
kind: ReplicationController
metadata:
  name: bigcouch
spec:
  replicas: 3
  selector:
    app: bigcouch
    project: valuphone
  template:
    metadata:
      name: bigcouch
      labels:
        app: bigcouch
        role: document-db
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
        - name: bigcouch-admin-secret
          secret:
            secretName: bigcouch-admin-secret
      containers:
        - name: bigcouch
          image: callforamerica/bigcouch
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
            - name: bigcouch-admin-secret
              readOnly: true
              mountPath: /etc/secrets/bigcouch
          ports:
            - name: data
              protocol: TCP
              containerPort: 5984
            - name: admin
              protocol: TCP
              containerPort: 5986
        - name: epmd
          image: callforamerica/epmd
        - name: dns
          image: callforamerica/go-dnsmasq
      restartPolicy: Always