apiVersion: v1
kind: Service
metadata:
  name: bigcouchbal
  labels:
    app: bigcouch
spec:
  # clusterIP: None
  selector:
    app: bigcouch
  ports:
    - name: data
      protocol: TCP
      port: 5984
    - name: admin
      protocol: TCP
      port: 5986
