apiVersion: apps/v1alpha
kind: PetSet
metadata:
  name: bigcouch
spec:
  serviceName: bigcouch
  replicas: 3
  template:
    metadata:
      labels:
        app: bigcouch
        project: valuphone
        environment: production
      annotations:
        pod.alpha.kubernetes.io/initialized: 'true'
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "register-service",
            "image": "callforamerica/init-register-service",
            "imagePullPolicy": "Always",
            "args": ["bigcouch"]
          }
        ]'
    spec:
      containers:
        - name: bigcouch
          image: callforamerica/bigcouch:petset-experiment
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
            - name: bigcouch-admin-secret
              readOnly: true
              mountPath: /etc/secrets/bigcouch
            - name: bigcouch-data
              mountPath: /mnt/bigcouch-data
          env:
            - name: MOUNT_PERSISTENT_VOLUME
              value: 'true'
          ports:
            - name: data
              protocol: TCP
              containerPort: 5984
            - name: admin
              protocol: TCP
              containerPort: 5986
          resources:
            requests:
              cpu: 2
              memory: 2G
            # limits:
            #   cpu: 2
            #   memory: 4G
          readinessProbe:
            httpGet:
              path: /_stats
              port: 5986
            initialDelaySeconds: 60
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /_stats
              port: 5986
            initialDelaySeconds: 60
            timeoutSeconds: 15
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
        - name: bigcouch-admin-secret
          secret:
            secretName: bigcouch-admin-secret
      volumeClaimTemplates:
        - metadata:
            name: bigcouch-data
            annotations:
              volume.alpha.kubernetes.io/storage-class: anything
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
      restartPolicy: Always
