kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigcouch-bigcouch-0
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigcouch-bigcouch-1
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigcouch-bigcouch-2
  labels:
    app: bigcouch
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
