kind: Pod
apiVersion: v1
metadata:
  name: bigcouch
  labels:
    app: bigcouch
    role: document-db
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
    - name: bigcouch-admin-secret
      secret:
        secretName: bigcouch-admin-secret
    - name: bigcouch-data
      persistentVolumeClaim:
        claimName: bigcouch-data
  containers:
    - name: bigcouch
      image: callforamerica/bigcouch
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
        - name: bigcouch-admin-secret
          readOnly: true
          mountPath: /etc/secrets/bigcouch
        - name: bigcouch-data
          mountPath: /mnt/bigcouch-data
      env:
        - name: KUBERNETES_USE_PERSISTENT_VOLUME
          value: 'true'
      ports:
        - name: data
          protocol: TCP
          containerPort: 5984
        - name: admin
          protocol: TCP
          containerPort: 5986
    - name: dns
      image: callforamerica/go-dnsmasq
  restartPolicy: Always