apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bigcouch
spec:
  template:
    metadata:
      name: bigcouch
      labels:
        app: bigcouch
        project: valuphone
        environment: production
    spec:
      hostNetwork: true
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
        - name: bigcouch-data
          persistentVolumeClaim:
            claimName: bigcouch-data
      containers:
        - name: bigcouch
          image: callforamerica/bigcouch
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
            - name: bigcouch-data
              mountPath: /mnt/bigcouch-data
          env:
            - name: KUBERNETES_USE_PERSISTENT_VOLUME
              value: 'true'
            - name: KUBERNETES_HOSTNAME_FIX
              value: 'false'
          ports:
            - name: data
              protocol: TCP
              containerPort: 5984
            - name: admin
              protocol: TCP
              containerPort: 5986
          resources:
            requests:
              cpu: 2
              memory: 4G
            # limits:
            #   cpu: 
            #   memory: 
          readinessProbe:
            httpGet:
              path: /_stats
              port: 5986
            initialDelaySeconds: 60
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /_stats
              port: 5986
            initialDelaySeconds: 60
            timeoutSeconds: 15
      restartPolicy: Always